import "bootstrap/dist/css/bootstrap.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import { useEffect } from "react";
import { GlobalStyle } from "../styles/globalStyles";

export default function App({ Component, pageProps }: AppProps) {
  useEffect(() => {
    require("bootstrap/dist/js/bootstrap");
  }, []);

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Kayo Elias | FullStack Developer</title>
      </Head>
      <GlobalStyle />
      <Component {...pageProps} />
    </>
  );
}
